[theme]
primaryColor = "#007D89"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F5F6"
textColor = "#575757"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
